### PR TITLE
8258216: Allow Nashorn to operate when not loaded as a JPMS module

### PR DESCRIPTION
**Pull request by szegedi**
Allow Nashorn to operate when not loaded as a JPMS module

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8258216](https://bugs.openjdk.java.net/browse/JDK-8258216): Allow Nashorn to operate when not loaded as a JPMS module

### Download
`$ git fetch https://git.openjdk.java.net/nashorn pull/9/head:pull/9`
`$ git checkout pull/9`

### CODE REVIEW

**Review by sundararajana — COMMENTED** [review]
Have was non-modular nashorn tested? Don't the tests assume that nashorn is run as module?

**Comment by szegedi** [comment]
Well, I did some light testing on the command line myself. I have this minimal application:
```java
import javax.script.*;

public class X {
    public static void main(String[] args) throws ScriptException {
        ScriptEngineManager factory = new ScriptEngineManager(); 
        ScriptEngine engine = factory.getEngineByName("nashorn"); 
        engine.eval("print('Hello, World!');");
    }
}
```
and running it from Nashorn directory (after JAR is built) with:
```
java -classpath build/nashorn/dist/nashorn.jar:build/nashorn/dependencies/asm-7.3.1.jar:build/nashorn/dependencies/asm-util-7.3.1.jar X.java
```
Before the changes it obviously causes:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.openjdk.nashorn.api.scripting.NashornScriptEngine$1.run(NashornScriptEngine.java:128)
	at org.openjdk.nashorn.api.scripting.NashornScriptEngine$1.run(NashornScriptEngine.java:124)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at org.openjdk.nashorn.api.scripting.NashornScriptEngine.<init>(NashornScriptEngine.java:124)
	at org.openjdk.nashorn.api.scripting.NashornScriptEngineFactory.getScriptEngine(NashornScriptEngineFactory.java:150)
	at java.scripting/javax.script.ScriptEngineManager.getEngineByName(ScriptEngineManager.java:241)
	at X.main(X.java:6)
Caused by: java.lang.IllegalArgumentException: Null module name
	at java.base/jdk.internal.module.Checks.requireModuleName(Checks.java:46)
	...
```
while running it after the changes outputs
```
Hello, World!
```
as expected. 

You're right that `ant test` target runs all the tests with Nashorn loaded as a module; that's still the preferred way. I'm doing this to foster adoption as there's a report that Nashorn doesn't work when Spring Boot based apps load it (as SB uses classpath to load app depedencies) and the referenced JBS issue was also filed by a person who seems to be on the JAX-RS expert group and is an Eclipse committer, so I suspect there might be something there too (not confirmed.) I might try to modify the test script locally for a one-time run; I'd be reluctant to add module/non-module to the test matrix.

**Comment by szegedi** [comment]
> Have was non-modular nashorn tested? Don't the tests assume that nashorn is run as module?

@sundararajana I created a [test-demodulator](https://github.com/szegedi/nashorn/compare/demodulator...szegedi:test-demodulator?expand=1) branch in my own fork of the repo building on top of this branch that's running tests with Nashorn on classpath instead of on module path.
You'll notice I moved two tests into "currently failing" in that branch as they're directly testing the module system. All other tests pass. Note that that branch is very hacky and is only meant to demonstrate the correctness of this code one time, it will not be submitted as a PR. As I said, I'd rather not add non-modular execution to the test matrix in general, at least not for now.

**Review by sundararajana — COMMENTED** [review]
Looks good

**Pull request merged**
